/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 03 21:15:19 GMT 2023
 */

package com.formento.cadastro.security.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.formento.cadastro.security.service.JwtUsuarioServiceServiceImpl;
import com.formento.cadastro.service.UsuarioService;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JwtUsuarioServiceServiceImpl_ESTest extends JwtUsuarioServiceServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JwtUsuarioServiceServiceImpl jwtUsuarioServiceServiceImpl0 = new JwtUsuarioServiceServiceImpl();
      UsuarioService usuarioService0 = mock(UsuarioService.class, new ViolatedAssumptionAnswer());
      doReturn((Optional) null).when(usuarioService0).getByEmail(anyString());
      Injector.inject(jwtUsuarioServiceServiceImpl0, (Class<?>) JwtUsuarioServiceServiceImpl.class, "usuarioService", (Object) usuarioService0);
      Injector.validateBean(jwtUsuarioServiceServiceImpl0, (Class<?>) JwtUsuarioServiceServiceImpl.class);
      // Undeclared exception!
      try { 
        jwtUsuarioServiceServiceImpl0.loadUserByUsername("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.formento.cadastro.security.service.JwtUsuarioServiceServiceImpl", e);
      }
  }
}
